Pelicula/Controllers/RoleManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pelicula.Areas.Identity.Data;
using Pelicula.Models;
using Pelicula.Models.Table;

namespace Pelicula.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleManagementController : Controller
    {
        // Administrador de usuarios
        private readonly UserManager<ApplicationUser> userManager;
        // Administrador de funciones
        private readonly RoleManager<IdentityRole> roleManager;
        // Clase de contexto de datos
        private readonly PeliculaContext _context;

        public RoleManagementController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, PeliculaContext context)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            _context = context;
        }


        [HttpGet]
        public IActionResult Index()
        {
            //obtener todos los usuarios y los envia a la vista
            var name = userManager.GetUserName(User);
            List<ApplicationUser> users = new List<ApplicationUser>();
            if(name == null)
            {
                users = userManager.Users.ToList();
            }
            else
            {
                users = userManager.Users.Where(d => d.UserName != name).ToList();   //ToList().Where(d => d.UserName != name).ToList();
            }
            return View(users);
        }
        [HttpGet]
        public async Task<IActionResult> Details(string userId)
        {
            if(userId == null)
            {
                return RedirectToAction(nameof(PageNotFound));
            }
            //Encontrar usuario por ID de usuario
            // Agregar nombre de usuario a ViewBag
            //obtener userRole de usuarios y enviar para ver
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.Error = "El Id del Usuario no es valido";
                return RedirectToAction(nameof(PageNotFound));
            }
            ViewBag.UserName = user.UserName;
            var userRoles = await userManager.GetRolesAsync(user);
            return View(userRoles);
        }
        [HttpGet]
        public IActionResult AddRole()
        {
            return RedirectToAction(nameof(DisplayRoles));
        }
        //[HttpPost]
        //public async Task<IActionResult> AddRole(string role)
        //{
        //    //crear un nuevo rol usando roleManager
        //    //return to displayRoles
        //    await roleManager.CreateAsync(new IdentityRole(role));
        //    return RedirectToAction(nameof(DisplayRoles));
        //}
        [HttpGet]
        public IActionResult DisplayRoles()
        {
            //Obtiene todos los roles y se los pasa a la vista
            DisplayRol r = new DisplayRol();
            r.roles = roleManager.Roles.ToList();
            return View(r);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisplayRoles([Bind("role,roles")] DisplayRol rl)
        {
            if (!ModelState.IsValid)
            {
                rl.roles = roleManager.Roles.ToList();
                return View(rl);
            }
            await roleManager.CreateAsync(new IdentityRole(rl.role));
            return RedirectToAction(nameof(DisplayRoles));
        }
        [HttpGet]
        public IActionResult AddUserToRole()
        {
            //Optiene todos los usuarios
            //Optiene todos los roles
            //crear lista de selección y pasar usando viewBag
            var users = userManager.Users.ToList();
            var roles = roleManager.Roles.ToList();

            // Primer paramentro es el que se optiene y el segundo es el que se muetra
            ViewBag.Users = new SelectList(users, "Id", "UserName");
            ViewBag.Roles = new SelectList(roles, "Name", "Name");
            
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddUserToRole([Bind("UserId,RoleName")] UserRole userRole)
        {
            // Valida que el modelo sea valido
            if (ModelState.IsValid)
            {
                //Encuentra el usuario por el ID
                //Asigna el rol al usuario
                //Redirecciona al index
                var user = await userManager.FindByIdAsync(userRole.UserId);
                await userManager.AddToRoleAsync(user, userRole.RoleName);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var users = userManager.Users.ToList();
                var roles = roleManager.Roles.ToList();

                ViewBag.Users = new SelectList(users, "Id", "UserName");
                ViewBag.Roles = new SelectList(roles, "Name", "Name");
                return View(userRole);
            }

        }
        [HttpGet]
        public async Task<IActionResult> RemoveUserRole(string role, string userName)
        {
            //get user from userName
            //remove role of user using userManager
            //return to details with parameter userId

            var user = await userManager.FindByNameAsync(userName);

            var result = await userManager.RemoveFromRoleAsync(user, role);

            return RedirectToAction(nameof(Details), new { userId = user.Id });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveRole(string role)
        {
            //Se optiene el nombre del rol mediante su nombre
            //Elimina el rol usando roleManager
            //Redirecciona a Displayroles

            var roleToDelete = await roleManager.FindByNameAsync(role);
            var result = await roleManager.DeleteAsync(roleToDelete);

            return RedirectToAction(nameof(DisplayRoles));
        }
        // GET: PeliculaRepositories/Delete/5
        public async Task<IActionResult> Delete(string? userId)
        {
            if (userId == null)
            {
                return NotFound();
            }

            var user = await _context.AspNetUsers.FindAsync (userId);
            if (user == null)
            {
                return NotFound();
            }
            
            return View(user);

        }

        //POST: PeliculaRepositories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string userId)
        {
            //var userRemove = await _context.AspNetUsers.FindAsync(userId);
            var user = await userManager.FindByIdAsync(userId);
            await userManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }

        [Route("404")]
        public IActionResult PageNotFound()
        {
            return View();
        }


    }
}

Pelicula/ViewComponents/DropdownGenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Pelicula.Models.Table;
using Microsoft.EntityFrameworkCore;

namespace Pelicula.ViewComponents
{
    public class DropdownGenerosViewComponent : ViewComponent
    {
        private readonly PeliculaContext _context;
        public DropdownGenerosViewComponent(PeliculaContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cm = await _context.Generos.ToListAsync();
            return View(cm);
        }
    }
}

Pelicula/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout.cshtml";
}
<br />

<div class="container">
    <div class="row align-items-center text-center " >
        <div class="col-8 offset-2">
            <a asp-action="AddRole" asp-controller="RoleManagement" class="btn btn-outline-primary btn-block">Nuevo Rol</a>
            <a asp-action="DisplayRoles" asp-controller="RoleManagement" class="btn btn-outline-primary btn-block">Ver Roles</a>
            <a asp-action="AddUserToRole" asp-controller="RoleManagement" class="btn btn-outline-primary btn-block">Asignar</a>
            <a asp-action="Index" asp-controller="RoleManagement" class="btn btn-outline-primary btn-block">Regresar</a>
        </div>
    </div>
    <br />
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</div>

Pelicula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>@ViewData["Title"] - Pelicula</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js" integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Pelicula.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3 ">
        <div class="container">
            <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Pelicula</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    
                </ul>
            </div>
            <partial name="_LoginPartial"/>
        </div>
    </nav>
    
    <div class="container-lg">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
 
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pelicula - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <div class="loaderbody" id="loaderbody" style="display:none">
        <div class="loader"></div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
    
</body>
</html>

Pelicula/Views/Shared/_PeliculaLayout.cshtml
@{
    Layout = "_Layout.cshtml";
}

<html>

<body>
    <br />
    <div class="container">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-lg">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="1">Accion</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="3">Aventura</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="6">Comedia</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="15">Terror</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="7">Crimen</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="28">Suspenso</a>
                            <a class="btn btn-outline-primary btn-block" asp-action="PeliculasGeneros" asp-controller="Home" asp-route-id="11">Fantasia</a>
                        </div>
                        @await Component.InvokeAsync("DropdownGeneros") 
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" name="MovieSearch"
                            value="@ViewData["GetMovies"]" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit" asp-action="Index" asp-controller="Home">Buscar</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container-lg">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <script type="text/javascript" src="Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="Scripts/jquery-2.1.1.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>

</html>

Pelicula/Views/Shared/_PelicutaPartial.cshtml
@model IEnumerable<PeliculaRepository>
<section class="main-container">
    <div class="location">
        <div class="box">
            @foreach (var movie in Model)
            {
                <a  asp-action="Detail" asp-route-id="@movie.IdPelicula">
                    <img src="@movie.LinkImagen" width="200px" height="250px" alt="@movie.Titulo" title=@movie.Titulo>
                        @movie.Titulo
                </a>
            }
        </div>
    </div>
</section>